### ISSUE TITLE
Arrow keys work only when NumLock is off

### ISSUE THREAD

**Issue by eitchtee** [ChaoticAlexander/helldivers2-stratagem-activator#1]
I've found that when using the default configuration (arrow keys), the stratagems activation only works if NumLock is off.

Doing some minor testing with Autohotkey for key detection, it seems that when NumLock is off, the key pressed in read as NumpadUp, NumpadDown, etc.
![image](https://github.com/ChaoticAlexander/helldivers2-stratagem-activator/assets/10510126/d40bd7a9-0dcf-4d99-a77c-aebe86eb32bf)

But when NumLock is On, the keys are read as Numpad8, Numpad4, etc.
![image](https://github.com/ChaoticAlexander/helldivers2-stratagem-activator/assets/10510126/54c5eb35-379a-43a4-b30b-505b58a89bbd)

Instead of Up, Down, Right, etc. for the proper arrows keys
![image](https://github.com/ChaoticAlexander/helldivers2-stratagem-activator/assets/10510126/ef2d8442-bdcd-46f5-b96c-f32430396c67)

According to https://www.toptal.com/developers/keycode the Arrow Keys and Numpad Arrow Keys do shame the same code, for example Up Arrow and NumpadUp are both code 38, so I'm not sure if your current implementation is able to distinguish between the two for a proper fix.

**Comment by ChaoticAlexander** [comment]
First of all thank you for looking into this.

I am aware of this issue and I think this is a technical limitation due to using DIK (direct input keys) to emit the keyboard events.
Since the codes for both numpad arrows and regular arrows are the same, I'm not sure this issue can be resolved.

I tried to instead use a different method of emitting the events, by using VIK codes (virtual input keys), but to no avail, as the game no longer recognizes the input. I suspect this might have to do with the anti-cheat system that the game is using.

I'll continue to look into it, but given the current facts, I'm not too hopeful.

**Comment by eitchtee** [comment]
Yes, the Anti-cheat is very aggressive at the moment, pretty much nothing but this software works atm, so thank you for the work!

Pressing NumLock is easy enough for this to not be a deal-breaker, pretty sure loupedeck and autohotkey could deal with this automatically even.

---

I did find _something_, but I didn't have the time to test on Helldivers 2 to see if the anti-cheat catches it, fingers crossed it doesn't:

The [documentation](https://learn.microsoft.com/en-US/windows/win32/api/winuser/ns-winuser-keybdinput?redirectedfrom=MSDN) mentions [`KEYEVENTF_EXTENDEDKEY`](https://learn.microsoft.com/en-us/windows/win32/inputdev/about-keyboard-input#extended-key-flag) as a `dwFlags` with value 0x0001

So, by simply adding one byte to the following constants

```python
KEYEVENTF_KEYDOWN = 0x0009  # was 0x0008
KEYEVENTF_KEYUP = 0x0003  # was 0x0002
```

Made codes 75 (left), 77 (right), 72 (up), 80 (down) be read as proper arrow keys on AutoHoKey even with NumLock On

As a caveat, this seems to breaks Numpad support, as all keys will be read as their extended version (further testing needed), so this probably should be a flag on the configuration.

**Comment by eitchtee** [comment]
> I did find _something_, but I didn't have the time to test on Helldivers 2 to see if the anti-cheat catches it, fingers crossed it doesn't:

Quick update:  Testing inside the game is really painful, but can confirm this method works

**Comment by ChaoticAlexander** [comment]
That's an amazing find!
I don't think I'd have figured this one out, so this is indeed a huge help.

With this in mind, however, I'll try to think of a way to maybe keep the numpad support as well.

Seriously, huge thanks for this!

**Comment by ChaoticAlexander** [comment]
@eitchtee managed to get the extended keys working. Verify, if you want, and if it works feel free to close this

**Comment by eitchtee** [comment]
Working beautifully @ChaoticAlexander
Thank you for taking the time to fix this
