### ISSUE TITLE
Home keymap sends 7 with NumLock on

### ISSUE THREAD

**Issue by zaquaz** [ChaoticAlexander/helldivers2-stratagem-activator#13]
I've noticed that with NumLock on, Home sends 7 with this app, whereas others tend to send the correct key.

~I've worked around it currently by disabling NumLock in the BIOS.~

So far I've not been able to figure out how to get around this properly.

**Comment by zaquaz** [comment]
https://github.com/ChaoticAlexander/helldivers2-stratagem-activator/pull/14

I've added this pull request to include detection of home extended.

**Comment by ChaoticAlexander** [comment]
@zaquaz Please check the latest release and let me know if the issue is fixed for you :)
