### ISSUE TITLE
shorter delay between button pressing and activation

### ISSUE THREAD

**Issue by Burncycle3008** [ChaoticAlexander/helldivers2-stratagem-activator#17]
First off thanks very MUCH!  This is awesome and now I can actually use the razer stream deck with HD2.  I love it!  I want to know if there is a way to shorten the delay from when I press the button on the stream deck to the actual stratagem getting called in.  I know virtually nothing about python scripting but am an experienced computer veteran capable of teaching myself new things.

**Comment by ChaoticAlexander** [comment]
Oh just try the unpacked version, it should speed things up a bit.
While the packed version is more convenient, as you only have one file, it takes a bit longer to start executing commands because it has to first unpack everything on each run.
Hope that helps! :)

**Comment by Burncycle3008** [comment]
Yes!  Much quicker.  You'd think you wouldn't notice a difference between waiting 50-75ms vs. 25-50 but it's pretty clear when speed matters.  You rock my dude!
